version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"  # Map local port 80 to container port 3000
    environment:
      - VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL} # Set backend URL via .env
    volumes:
      - .:/app  # Mount local directory into the container for live updates
      - /app/node_modules # Avoid overriding node_modules
    command: npm run dev  # Run the app in development mode
