version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL} # Make sure to set this in your .env file or locally
    volumes:
      - .:/app
      - /app/node_modules # Avoid overriding node_modules
    # command: npm run dev # If you want to run in dev mode
    # Or for production
    command: npm run build && serve -s build