version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URI=mysql+pymysql://root:root@db/cafe_db
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5